### ISSUE TITLE
Crash when session is removed while Birdwatch is running

### ISSUE THREAD

**Issue by n-st** [n-st/birdwatch#1]
```
Lost connection to bird:
Traceback (most recent call last):
  File "/opt/birdwatch/birdwatch", line 189, in watch_socket
    handler.get_changes()
  File "/opt/birdwatch/birdwatch", line 95, in get_changes
    del self.protocol_log[protocol]
KeyError: 'as65432'
```

**Comment by n-st** [comment]
Low priority, since this should be a very infrequent condition and `systemd` simply restarts the birdwatch service on failure anyway.
